In [6]:
import itertools
import numpy as np 

In [11]:
# Define parameter values
flux_array = np.arange(.4, .6, .05)
num_points = len(flux_array)
cap_array  = np.arange(.01, .3, .01)
ind_array  = np.arange(.01, .3, .01)

In [12]:
vals = np.array(np.meshgrid(flux_array, cap_array, ind_array)).T.reshape(-1, 3)

[[0.4  0.01 0.01]
 [0.4  0.02 0.01]
 [0.4  0.03 0.01]
 ...
 [0.55 0.27 0.29]
 [0.55 0.28 0.29]
 [0.55 0.29 0.29]]


In [14]:
# Write to text file
with open("param_values.txt", "w") as f:
    for i in range(len(vals)):
        line = f"{vals[i][0]:.4f} {vals[i][1]:.4f} {vals[i][2]:.4f}"
        f.write(line + "\n")